package com.pengyifan.leetcode;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random
 * position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <pre>
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 * </pre>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
  public char findTheDifference(String s, String t) {
    if (s == null) {
      return 0;
    }
    int[] countS = new int[26];
    for (char c : s.toCharArray()) {
      countS[c - 'a']++;
    }
    int[] countT = new int[26];
    for (char c : t.toCharArray()) {
      countT[c - 'a']++;
    }
    for (int i = 0; i < 26; i++) {
      if (countS[i] != countT[i]) {
        return (char) (i + 'a');
      }
    }
    return 0;
  }
}
